name: poke_romeo
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  relative_scale: ^2.0.0
  flutter: 
    sdk: flutter
  intl: ^0.17.0
  cached_network_image: ^3.2.1

dev_dependencies: 
  flutter_lints: ^2.0.0
  lints: 2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - lib/app/assets/images/logoNoPokemon.png


